---
title: "CV"
---

View [my full CV here](https://gerrymcquade.github.io/cv/GM_cv.pdf).

------------------------------------------------------------------------

#### Education

**Lancaster University** \| PhD Economics \| 2020 -

*Advisors: Catherine Porter & Saurabh Singhal*

**University of Oxford, ODID** \| Visiting Research Student \| Trinity term 2023

*Host: Marta Favara*

**University of Edinburgh** \| MSc Economics (SGPE) \| 2019 - 2020

*Advisors: Robert Mochrie & Catherine Porter*

**Heriot Watt University** \| MA Economics \| 2015 - 2019

*Advisors: Robert Mochrie*

------------------------------------------------------------------------

#### Research Experience

**Lancaster University** \| *Lancaster, UK* \| Teaching Associate \| 2024-

**Grupo De Análisis para el Desarrollo** \| *Lima, Peru* \| Visiting Researcher \| Winter 2023

**Queen Mary University London** \| *London, UK* \| RA to Simon Franklin \| 2022

**Young Lives** \| *Oxford, UK* \| Research Consultant \| 2021 - 2023

**Lancaster University** \| *Lancaster, UK* \| RA to Catherine Porter \| 2020

**Office for National Statistics** \| *Newport, UK* \| Statistical Research Officer \| 2019

**Health Economics Research Unit** \| *Aberdeen, UK* \| Research Intern \| 2018

------------------------------------------------------------------------

#### Teaching

**Lancaster University** \| 2021 - 2024

-   Communicating Using Economic Data (ECON104) \| Seminars \| 2024-2025

-   EconHub \| Undergraduate helpdesk and revision sessions \| 2024-2025

-   Applied Economics (ECON229) \| Seminars \| 2021-2022

-   Quantitative Methods for Economics (ECON 103) \| Additional workshops \| 2022

-   LUMS Maths and Statistics Hub \| 1-to-1 Workshops \| 2021-2022

**Heriot Watt University** \| 2019 - 2020

-   Intermediate Microeconomics (C28IN) \| Workshops \| 2019-2020

-   Econometrics Project (C29EJ) \| Labs \| 2019
